[build]
builder = "NIXPACKS"
installCommand = "echo 'Skipping default install'"
buildCommand = "cd backend && npm install && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "node backend/src/server.js"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
